# Generated by Django 4.2.5 on 2023-12-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proj_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Proj_status',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(default=0, max_length=50)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='eEmail',
        ),
        migrations.AddField(
            model_name='employee',
            name='empId',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eCompany',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.company'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('eCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.employee')),
                ('pro_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.role')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='empRole',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.role'),
        ),
        migrations.AddField(
            model_name='project',
            name='pclient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.clients'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.proj_status'),
        ),
    ]
