# Generated by Django 4.2.5 on 2023-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0002_proj_status_role_remove_project_eemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
