# Generated by Django 4.2.5 on 2023-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0004_rename_role_role_role_alter_company_clogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cLogo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
