# Generated by Django 4.2.5 on 2023-12-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0006_alter_company_clogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cLogo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
