# Generated by Django 4.2.5 on 2023-12-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0007_alter_company_clogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='empId',
            fields=[
                ('Empid', models.CharField(max_length=50, primary_key='true', serialize=False, unique='true')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='eLname',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.empid'),
        ),
    ]
