# Generated by Django 4.2.5 on 2023-12-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0008_empid_alter_employee_elname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eLname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.empid'),
        ),
    ]
