# Generated by Django 4.2.5 on 2023-12-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0009_alter_employee_elname_alter_employee_empid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empid',
            table='empId',
        ),
    ]
