# Generated by Django 4.2.5 on 2023-12-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0011_employee_apps_employee_screenshot_employee_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cLogo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
