# Generated by Django 4.2.5 on 2023-12-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0013_alter_company_cname_alter_empid_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eCompany',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='empId',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='empRole',
        ),
        migrations.RemoveField(
            model_name='project',
            name='eCompany',
        ),
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pclient',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.DeleteModel(
            name='clients',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='empId',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Proj_status',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
