# Generated by Django 4.2.5 on 2023-12-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0018_employee_app_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='pname',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
